# one-hot encode and word2vec


baixe os 2 arquivo de aproximadamente 3gb (CBOW AND SKIPGRAM de 30 dimensoes)
http://nilc.icmc.usp.br/nilc/index.php/repositorio-de-word-embeddings-do-nilc

- Word Embeddings do NILC

e coloque seu caminho onde tive:
- [/content/drive/MyDrive/codealura/4-Word2Vec: interpretação da linguagem humana com Word embedding/cbow_s300.txt]

- [/content/drive/MyDrive/codealura/4-Word2Vec: interpretação da linguagem humana com Word embedding/skip_s300.txt]


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
artigo_treino = pd.read_csv("/content/drive/MyDrive/codealura/4-Word2Vec parte 1 and 2: interpretação da linguagem humana com Word embedding e treinamento de Word2Vec/treino.csv")
artigo_teste = pd.read_csv("/content/drive/MyDrive/codealura/4-Word2Vec parte 1 and 2: interpretação da linguagem humana com Word embedding e treinamento de Word2Vec/teste.csv")
artigo_treino.sample(5)

title  \
68403                                A língua impalpável   
22961  Após frente fria, SP deve ter domingo com temp...   
57930  Investigação sobre Rolls-Royce mostra passivid...   
64185  Bolsa fecha em alta de 2% guiada por ações de ...   
64311  Jovem reage a sequestro-relâmpago e mata assal...   

                                                    text        date  \
68403  Cheguei no vale de U-ah-hu numa manhã de domin...  2015-06-15   
22961  A frente fria que deixou o tempo instável na r...  2015-07-25   
57930  Frutas, flores e velas: 200 mil libras. Por an...  2017-05-05   
64185  A forte valorização das ações de bancos e da m...  2015-10-06   
64311  Vítima de um sequestro-relâmpago junto com a n...  2016-03-18   

        category       subcategory  \
68403    colunas  gregorioduvivier   
22961  cotidiano               NaN   
57930    mercado               NaN   
64185    mercado               NaN   
64311  cotidiano               NaN   

                                                    link  
68403  http://www1.folha.uol.com.br/colunas/gregoriod...  
22961  http://www1.folha.uol.com.br/cotidiano/2015/07...  
57930  http://www1.folha.uol.com.br/mercado/2017/05/1...  
64185  http://www1.folha.uol.com.br/mercado/2015/06/1...  
64311  http://www1.folha.uol.com.br/cotidiano/2016/03...

In [3]:
artigo_teste.sample(5)
artigo_teste.iloc[643].title

'Somos todos imprevisíveis'

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

texto =[
        "tenha um bom dia",
        "tenha um péssimo dia",
        "tenha um ótimo dia",
        "tenha um dia ruim python java alura caelum papa"

]

vetorizador = CountVectorizer()
vetorizador.fit(texto)

CountVectorizer()

In [5]:
print(vetorizador.vocabulary_)

{'tenha': 9, 'um': 10, 'bom': 1, 'dia': 3, 'péssimo': 7, 'ótimo': 11, 'ruim': 8, 'python': 6, 'java': 4, 'alura': 0, 'caelum': 2, 'papa': 5}


In [6]:
vetor_bom = vetorizador.transform(["bom"])
print(vetor_bom.toarray())
vetor_otimo = vetorizador.transform(["ótimo"])
print(vetor_otimo.toarray())

[[0 1 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 0 1]]


In [8]:
# [cbow] and [skip gram] || nilc - laboratorio da usp
#http://nilc.icmc.usp.br/nilc/index.php/repositorio-de-word-embeddings-do-nilc - Word Embeddings do NILC
# baixar o de 300 dimensoes  word2vc

# carregando modelo word2vec

In [ ]:
with open("/content/drive/MyDrive/codealura/4-Word2Vec parte 1 and 2: interpretação da linguagem humana com Word embedding e treinamento de Word2Vec/cbow_s300.txt") as file:
  for linha in range(10):
    print(next(file))

In [22]:
# carregamento de um modelo word2vec a partir de um arquivo.txt de key and vector
from gensim.models import KeyedVectors

modelo = KeyedVectors.load_word2vec_format("/content/drive/MyDrive/codealura/4-Word2Vec parte 1 and 2: interpretação da linguagem humana com Word embedding e treinamento de Word2Vec/cbow_s300.txt")

In [23]:
# vetor da palavra
modelo.get_vector('china')

array([-1.49033e-01,  1.26020e-01,  2.17628e-01,  1.82684e-01,
        1.65151e-01, -1.59660e-01, -2.34411e-01,  6.00570e-02,
        8.03680e-02,  2.87578e-01, -4.81100e-03, -5.68800e-02,
        2.15676e-01,  8.65540e-02,  1.25983e-01,  3.36157e-01,
       -1.83254e-01, -1.18499e-01,  1.13010e-02,  1.03814e-01,
        9.37640e-02,  2.90178e-01, -1.64395e-01, -1.13300e-02,
       -1.80676e-01, -1.15820e-02,  1.08728e-01,  1.65898e-01,
        9.37900e-02,  2.66767e-01, -1.29890e-02,  9.16030e-02,
        2.21292e-01, -1.36497e-01, -4.26350e-02, -1.30038e-01,
        2.17067e-01, -1.01963e-01, -3.70960e-02,  1.42155e-01,
        3.41109e-01,  2.46560e-01,  1.27458e-01,  5.72360e-02,
       -1.47962e-01, -1.60290e-02,  1.86533e-01,  7.71550e-02,
       -3.50024e-01, -4.06085e-01,  1.67131e-01, -4.75230e-02,
        5.13780e-02, -1.28224e-01,  1.06580e-02, -2.92652e-01,
        1.40540e-01, -4.57049e-01,  1.31094e-01,  2.03234e-01,
        2.94019e-01,  7.38370e-02,  1.11554e-01, -1.642

In [24]:
# palavras mais similares e vetores !!!!
print(modelo.most_similar('china'))
# faz a soma entre os dois vetores das palavras e busca as palavras mais próximas do vetor resultante
modelo.most_similar(positive=["brasil", "argentina"])

[('rússia', 0.7320705056190491), ('índia', 0.7241616249084473), ('tailândia', 0.701935887336731), ('indonésia', 0.6860769987106323), ('turquia', 0.6741335988044739), ('malásia', 0.6665689945220947), ('mongólia', 0.6593616008758545), ('manchúria', 0.658184826374054), ('urss', 0.6581669449806213), ('grã-bretanha', 0.6568097472190857)]


[('chile', 0.6781662702560425),
 ('peru', 0.634803295135498),
 ('venezuela', 0.6273865699768066),
 ('equador', 0.6037014126777649),
 ('bolívia', 0.6017141342163086),
 ('haiti', 0.5993806719779968),
 ('méxico', 0.596230685710907),
 ('paraguai', 0.5957703590393066),
 ('uruguai', 0.590367317199707),
 ('japão', 0.5893509387969971)]

In [25]:
# nuvens -> nuvem : estrelas -> estrela
# nuvens +  estrela - nuvem = estrelas

modelo.most_similar(positive=["nuvens", "estrela"], negative=["nuvem"])

[('estrelas', 0.5497430562973022),
 ('plêiades', 0.3791979253292084),
 ('colinas', 0.3746805489063263),
 ('trovoadas', 0.373703271150589),
 ('sombras', 0.37341946363449097),
 ('pombas', 0.3726757764816284),
 ('corredoras', 0.3640727400779724),
 ('cigarras', 0.36065396666526794),
 ('galáxias', 0.35754913091659546),
 ('luas', 0.3575345277786255)]

In [30]:
modelo.most_similar(positive=["médico", "mulher"], negative=["homem"])
modelo.most_similar(positive=["professor", "mulher"], negative=["homem"])
modelo.most_similar(positive=["delegado", "mulher"], negative=["homem"])

[('enfermeira', 0.5199974179267883),
 ('advogada', 0.4932612180709839),
 ('delegada', 0.49268317222595215),
 ('dama-de-companhia', 0.4576503336429596),
 ('madrasta', 0.45745649933815),
 ('esposa', 0.4566546678543091),
 ('geógrafa', 0.4557585120201111),
 ('namorada', 0.45138540863990784),
 ('cabeleireira', 0.4490765631198883),
 ('psicóloga', 0.4423496425151825)]

# VETORIZAÇÃO DE TEXTO
### https://web.stanford.edu/~jurafsky/slp3/6.pdf
    One-hot encoding: Nesta técnica, cada palavra em um vocabulário é representada por um vetor binário, onde todos os elementos são zeros, exceto um, que é um. Esse um indica a posição da palavra no vocabulário. Por exemplo, se tivermos um vocabulário de 1000 palavras, cada palavra seria representada por um vetor de 1000 elementos, com apenas um deles como 1 e os outros como 0.

    Word2Vec: É uma técnica de representação vetorial de palavras em espaço contínuo. Ela mapeia palavras para vetores de números reais de tal forma que palavras semelhantes estejam próximas umas das outras nesse espaço. Word2Vec é treinado em grandes corpora de texto usando redes neurais e pode capturar relações semânticas e sintáticas entre palavras.

    TF-IDF (Term Frequency-Inverse Document Frequency): Esta técnica atribui pesos às palavras com base em sua frequência no documento e em seu inverso na coleção de documentos. Isso destaca palavras que são frequentes em um documento específico, mas não são comuns em toda a coleção.

    GloVe (Global Vectors for Word Representation): Similar ao word2vec, o GloVe também mapeia palavras em vetores de números reais. No entanto, ele é treinado usando estatísticas globais de coocorrência de palavras em vez de uma rede neural específica.

    FastText: Desenvolvido pelo Facebook AI Research (FAIR), o FastText é uma extensão do word2vec que inclui informações de subpalavras. Isso permite a representação de palavras que não estão no vocabulário, bem como a captura de informações morfológicas.

    BERT (Bidirectional Encoder Representations from Transformers): BERT é um modelo de linguagem baseado em transformers que é pré-treinado em grandes quantidades de texto. Embora seja mais conhecido por sua capacidade de realizar tarefas de processamento de linguagem natural (NLP), as representações vetoriais aprendidas pelo BERT também podem ser usadas para vetorização de palavras.

    Doc2Vec: Uma extensão do word2vec que não apenas aprende vetores para palavras, mas também para documentos inteiros. Cada documento é associado a um vetor, assim como as palavras são associadas a vetores no word2vec.

In [31]:
artigo_treino["title"].loc[12]

"Daniel Craig será stormtrooper em novo 'Star Wars', diz ator"

In [32]:
import nltk
import string
nltk.download("punkt")
def tokenizador(texto):
  texto = texto.lower()
  lista_alfanumerico = []
  for token_valido in nltk.word_tokenize(texto):
    if token_valido in string.punctuation: continue
    lista_alfanumerico.append(token_valido)
  return lista_alfanumerico


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [33]:
tokenizador("texto exemplo, 123.")

['texto', 'exemplo', '123']

In [55]:
import numpy as np

def combinacao_de_vetores_por_soma(palavras_numeros):
  vetor_resultante = np.zeros(300)
  for pn in palavras_numeros:
    try:
      vetor_resultante += modelo.get_vector(pn)
    except KeyError:
      if pn.isnumeric():
        pn = "0"*len(pn)
        vetor_resultante += modelo.get_vector(pn)
      else:
        vetor_resultante += modelo.get_vector("unknown")
  return vetor_resultante

In [59]:
"""
  Por conta do pré processamento feito no word embb, pode acontecer de
  uma palavra que não é comum ser colocada como UNKNOWN e quando houver
  um número pode dar erro também, pois no pré processamento, todos os
  número foram trocados por zero.
"""
palavras_numeros = tokenizador("texto caleemmi")  # teste com "texto caleemmi || texto 928"
vetor_texto = combinacao_de_vetores_por_soma(palavras_numeros)
len(vetor_texto), vetor_texto

(300,
 array([ 4.04902007e-01,  1.61033005e-01, -1.28350001e-01,  4.63957988e-01,
        -3.79070006e-02,  9.79099981e-02,  6.06219992e-02,  2.50669867e-02,
        -1.45315003e-01, -1.20187001e-01, -1.45029984e-02, -3.97820026e-02,
        -5.53439990e-01,  3.39491010e-01,  4.74720001e-02,  2.32610006e-01,
        -7.91507989e-01,  7.62100518e-03, -4.30413000e-01, -1.62210986e-01,
        -1.36736006e-01, -2.92862996e-01, -7.81050026e-02,  4.56106991e-01,
        -1.08597010e-01, -1.72903001e-01, -3.94289017e-01, -7.94299692e-03,
         1.54560007e-01, -1.81829929e-02, -1.44808993e-01, -1.92361996e-01,
         5.27470000e-02,  2.77960012e-02,  3.75599414e-03,  2.15162002e-01,
         2.41512008e-01,  2.07674988e-01,  1.77449007e-01,  2.00845003e-01,
         1.08239995e-02, -1.03557003e-01,  4.52470034e-02,  3.54460012e-02,
         2.74897987e-01, -7.71570001e-02,  4.26173002e-01,  4.57773015e-01,
         2.98846003e-01,  2.85166003e-01,  1.75556996e-01,  1.93372004e-01,
      

In [65]:
# vetorizando treino e texto
import numpy as np

def matriz_vetores(textos):
  x = len(textos)
  y = 300
  matriz = np.zeros((x,y))

  for i in range(x):
    palavras_numeros = tokenizador(textos.iloc[i])
    matriz[i] = combinacao_de_vetores_por_soma(palavras_numeros)

  return matriz


matriz_vetores_treino = matriz_vetores(artigo_treino.title)
matriz_vetores_teste = matriz_vetores(artigo_teste.title)


In [68]:
matriz_vetores_treino.shape, matriz_vetores_teste.shape

((90000, 300), (20513, 300))

In [71]:
artigo_treino.category[0:5]

0        mundo
1        mundo
2        mundo
3    cotidiano
4      mercado
Name: category, dtype: object

In [73]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(max_iter=200)
LR.fit(matriz_vetores_treino, artigo_treino.category)

LogisticRegression(max_iter=200)

In [85]:
LR.n_iter_

array([118], dtype=int32)

In [86]:
# score todas categorias
LR.score(matriz_vetores_teste, artigo_teste.category)

0.7957880368546775

In [87]:
artigo_teste.category.unique()

array(['colunas', 'esporte', 'mercado', 'cotidiano', 'mundo', 'ilustrada'],
      dtype=object)

In [93]:
from sklearn.metrics import classification_report
label_prevista = LR.predict(matriz_vetores_teste)

CR = classification_report(artigo_teste.category, label_prevista)
print(CR)

              precision    recall  f1-score   support

     colunas       0.86      0.71      0.78      6103
   cotidiano       0.61      0.79      0.69      1698
     esporte       0.92      0.88      0.90      4663
   ilustrada       0.13      0.88      0.23       131
     mercado       0.84      0.79      0.81      5867
       mundo       0.74      0.86      0.79      2051

    accuracy                           0.80     20513
   macro avg       0.68      0.82      0.70     20513
weighted avg       0.83      0.80      0.81     20513



In [96]:
from sklearn.dummy import DummyClassifier

DC = DummyClassifier()
DC.fit(matriz_vetores_treino, artigo_treino.category)

DummyClassifier()

In [91]:
from sklearn.metrics import classification_report
label_prevista_dc = DC.predict(matriz_vetores_teste)

CR_dummy = classification_report(artigo_teste.category, label_prevista_dc, zero_division=1)
print(CR_dummy)

              precision    recall  f1-score   support

     colunas       0.30      1.00      0.46      6103
   cotidiano       1.00      0.00      0.00      1698
     esporte       1.00      0.00      0.00      4663
   ilustrada       1.00      0.00      0.00       131
     mercado       1.00      0.00      0.00      5867
       mundo       1.00      0.00      0.00      2051

    accuracy                           0.30     20513
   macro avg       0.88      0.17      0.08     20513
weighted avg       0.79      0.30      0.14     20513



# skip gram

In [ ]:
# skip gram
from gensim.models import KeyedVectors

modelo_skipgram = KeyedVectors.load_word2vec_format("/content/drive/MyDrive/codealura/4-Word2Vec parte 1 and 2: interpretação da linguagem humana com Word embedding e treinamento de Word2Vec/skip_s300.txt")

In [92]:
import numpy as np

def combinacao_de_vetores_por_soma_skipgram(palavras_numeros):
  vetor_resultante = np.zeros(300)
  for pn in palavras_numeros:
    try:
      vetor_resultante += modelo_skipgram.get_vector(pn)
    except KeyError:
      if pn.isnumeric():
        pn = "0"*len(pn)
        vetor_resultante += modelo_skipgram.get_vector(pn)
      else:
        vetor_resultante += modelo_skipgram.get_vector("unknown")
  return vetor_resultante

In [ ]:
# vetorizando treino e texto
import numpy as np

def matriz_vetores_skipgram(textos):
  x = len(textos)
  y = 300
  matriz = np.zeros((x,y))

  for i in range(x):
    palavras_numeros = tokenizador(textos.iloc[i])
    matriz[i] = combinacao_de_vetores_por_soma_skipgram(palavras_numeros)

  return matriz


matriz_vetores_treino_skipgram = matriz_vetores_skipgram(artigo_treino.title)
matriz_vetores_teste_skipgram = matriz_vetores_skipgram(artigo_teste.title)

In [ ]:
# treino LogisticRegression
from sklearn.linear_model import LogisticRegression

LR_skipgram = LogisticRegression(max_iter=1000)
LR_skipgram.fit(matriz_vetores_treino_skipgram, artigo_treino.category)

In [ ]:
# previsao
from sklearn.metrics import classification_report

label_prevista_skipgram = LR_skipgram.predict(matriz_vetores_teste_skipgram)
CR_skipgram = classification_report(artigo_teste.category, label_prevista_skipgram)
print(CR_skipgram)

In [ ]:
# treino DummyClassifier

from sklearn.dummy import DummyClassifier

DC_skipgram = DummyClassifier()
DC_skipgram.fit(matriz_vetores_treino_skipgram, artigo_treino.category)

In [ ]:
# previsao
from sklearn.metrics import classification_report

label_prevista_skipgram_dummy = DC_skipgram.predict(matriz_vetores_teste_skipgram)
CR_skipgram_dummy = classification_report(artigo_teste.category, label_prevista_skipgram_dummy)
print(CR_skipgram_dummy)

In [100]:
print('ok')

ok
